language: node_js
node_js:
  - 0.10
before_script:
  - node test/server.js &
  - sleep 5
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout 1.0.0-RC1
  - cd ..
  - export PATH=$PATH:$PWD/casperjs/bin/
script: make test
